// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using RssToolkit.Rss;
namespace RssToolkitUnitTest
{
    /// <summary>
    ///This is a test class for RssToolkit.Rss.RssTextInput and is intended
    ///to contain all RssToolkit.Rss.RssTextInput Unit Tests
    ///</summary>
    [TestClass()]
    public class RssTextInputTest
    {
        private TestContext testContextInstance;
        private static RssDocument rss;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class

        [ClassInitialize()]
        public static void MyClassInitialize(TestContext testContext)
        {
            rss = RssToolkitUnitTest.Utility.RssUtility.GetRssDocumentFromXml();
        }
        
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for Description
        ///</summary>
        [TestMethod()]
        public void RssTextInputDescriptionTest()
        {
            Assert.AreEqual("Explains the text input area.", rss.Channel.TextInput.Description , "RssToolkit.Rss.RssTextInput.Description was not set correctly.");
        }

        /// <summary>
        ///A test for Link
        ///</summary>
        [TestMethod()]
        public void RssTextInputLinkTest()
        {
            Assert.AreEqual("The URL of the CGI script that processes text input requests.", rss.Channel.TextInput.Link, "RssToolkit.Rss.RssTextInput.Description was not set correctly.");
        }

        /// <summary>
        ///A test for Name
        ///</summary>
        [TestMethod()]
        public void RssTextInputNameTest()
        {
            Assert.AreEqual("The name of the text object in the text input area.", rss.Channel.TextInput.Name, "RssToolkit.Rss.RssTextInput.Description was not set correctly.");
        }

        /// <summary>
        ///A test for Title
        ///</summary>
        [TestMethod()]
        public void RssTextInputTitleTest()
        {
            Assert.AreEqual("The label of the Submit button in the text input area.", rss.Channel.TextInput.Title, "RssToolkit.Rss.RssTextInput.Description was not set correctly.");
        }
    }
}
