// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using RssToolkit.Opml;
namespace RssToolkitUnitTest
{
    /// <summary>
    ///This is a test class for RssToolkit.Opml.OpmlHead and is intended
    ///to contain all RssToolkit.Opml.OpmlHead Unit Tests
    ///</summary>
    [TestClass()]
    public class OpmlHeadTest
    {
        private TestContext testContextInstance;
        private static OpmlDocument target;


        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        [ClassInitialize()]
        public static void MyClassInitialize(TestContext testContext)
        {
            target = RssToolkitUnitTest.Utility.RssUtility.GetOpmlDocumentFromXml();
        }

        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion

        /// <summary>
        ///A test for DateCreated
        ///</summary>
        [TestMethod()]
        public void OpmlHeadDateCreatedTest()
        {
            Assert.AreEqual("Sat, 18 Jun 2005 12:11:52 GMT", target.Head.DateCreated, "RssToolkit.Opml.OpmlDocument.Head was not set correctly.");
        }

        /// <summary>
        ///A test for DateModified
        ///</summary>
        [TestMethod()]
        public void OpmlHeadDateModifiedTest()
        {
            Assert.AreEqual("Tue, 02 Aug 2005 21:42:48 GMT", target.Head.DateModified, "RssToolkit.Opml.OpmlDocument.Head was not set correctly.");
        }

        /// <summary>
        ///A test for Link
        ///</summary>
        [TestMethod()]
        public void OpmlHeadLinkTest()
        {
            Assert.AreEqual("http://www.microsoft.com", target.Head.Link, "RssToolkit.Opml.OpmlDocument.Head was not set correctly.");            
        }

        /// <summary>
        ///A test for OwnerEmail
        ///</summary>
        [TestMethod()]
        public void OpmlHeadOwnerEmailTest()
        {            
            Assert.AreEqual("someone@email.com", target.Head.OwnerEmail, "RssToolkit.Opml.OpmlDocument.Head was not set correctly.");
        }

        /// <summary>
        ///A test for OwnerName
        ///</summary>
        [TestMethod()]
        public void OpmlHeadOwnerNameTest()
        {
            Assert.AreEqual("Some One", target.Head.OwnerName, "RssToolkit.Opml.OpmlDocument.Head was not set correctly.");            
        }

        /// <summary>
        ///A test for Title
        ///</summary>
        [TestMethod()]
        public void OpmlHeadTitleTest()
        {
            Assert.AreEqual("mySubscriptions.opml", target.Head.Title, "RssToolkit.Opml.OpmlDocument.Head was not set correctly.");
        }
    }
}
