// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using RssToolkit.Opml;
namespace RssToolkitUnitTest
{
    /// <summary>
    ///This is a test class for RssToolkit.Opml.OpmlBody and is intended
    ///to contain all RssToolkit.Opml.OpmlBody Unit Tests
    ///</summary>
    [TestClass()]
    public class OpmlBodyTest
    {
        private TestContext testContextInstance;
        private static OpmlDocument target;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        [ClassInitialize()]
        public static void MyClassInitialize(TestContext testContext)
        {
            target = RssToolkitUnitTest.Utility.RssUtility.GetOpmlDocumentFromXml();
        }

        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for Outlines
        ///</summary>
        [TestMethod()]
        public void OpmlBodyOutlinesTest()
        {
            Assert.IsTrue(target.Body.Outlines.Count > 0, "RssToolkit.Opml.OpmlDocument.Body was not set correctly.");
            Assert.AreEqual("BBC News | News Front Page | UK Edition", target.Body.Outlines[0].Text, "RssToolkit.Opml.OpmlDocument.Body was not set correctly.");
            Assert.AreEqual("CNET News.com", target.Body.Outlines[1].Text, "RssToolkit.Opml.OpmlDocument.Body was not set correctly.");
        }
    }
}
