// ------------------------------------------------------------------------------
//<autogenerated>
//        This code was generated by Microsoft Visual Studio Team System 2005.
//
//        Changes to this file may cause incorrect behavior and will be lost if
//        the code is regenerated.
//</autogenerated>
//------------------------------------------------------------------------------
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace RssToolkitUnitTest
{
    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    internal class BaseAccessor
    {

        protected Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject m_privateObject;

        protected BaseAccessor(object target, Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType type)
        {
            m_privateObject = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject(target, type);
        }

        protected BaseAccessor(Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType type)
            :
                this(null, type)
        {
        }

        internal virtual object Target
        {
            get
            {
                return m_privateObject.Target;
            }
        }

        public override string ToString()
        {
            return this.Target.ToString();
        }

        public override bool Equals(object obj)
        {
            if (typeof(BaseAccessor).IsInstanceOfType(obj))
            {
                obj = ((BaseAccessor)(obj)).Target;
            }
            return this.Target.Equals(obj);
        }

        public override int GetHashCode()
        {
            return this.Target.GetHashCode();
        }
    }


    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    internal class RssToolkit_Opml_OutlineInfoAccessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("RssToolkit", "RssToolkit.Opml.OutlineInfo");

        internal RssToolkit_Opml_OutlineInfoAccessor(object target)
            :
                base(target, m_privateType)
        {
        }

        internal global::RssToolkit.Opml.OpmlOutline outline
        {
            get
            {
                global::RssToolkit.Opml.OpmlOutline ret = ((global::RssToolkit.Opml.OpmlOutline)(m_privateObject.GetField("outline")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("outline", value);
            }
        }

        internal int index
        {
            get
            {
                int ret = ((int)(m_privateObject.GetField("index")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("index", value);
            }
        }

        internal global::RssToolkit.Opml.OpmlOutline Outline
        {
            get
            {
                global::RssToolkit.Opml.OpmlOutline ret = ((global::RssToolkit.Opml.OpmlOutline)(m_privateObject.GetProperty("Outline")));
                return ret;
            }
        }

        internal int Index
        {
            get
            {
                int ret = ((int)(m_privateObject.GetProperty("Index")));
                return ret;
            }
        }

        internal static object CreatePrivate(global::RssToolkit.Opml.OpmlOutline ol, int index)
        {
            object[] args = new object[] {
                ol,
                index};
            Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("RssToolkit", "RssToolkit.Opml.OutlineInfo", new System.Type[] {
                    typeof(global::RssToolkit.Opml.OpmlOutline),
                    typeof(int)}, args);
            return priv_obj.Target;
        }
    }

    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    internal class RssToolkit_Rss_DownloadManager_CacheInfoAccessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("RssToolkit", "RssToolkit.Rss.DownloadManager+CacheInfo");

        internal RssToolkit_Rss_DownloadManager_CacheInfoAccessor(object target)
            :
                base(target, m_privateType)
        {
        }

        internal global::System.IO.Stream data
        {
            get
            {
                global::System.IO.Stream ret = ((global::System.IO.Stream)(m_privateObject.GetField("data")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("data", value);
            }
        }

        internal global::System.DateTime expiry
        {
            get
            {
                global::System.DateTime ret = ((global::System.DateTime)(m_privateObject.GetField("expiry")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("expiry", value);
            }
        }

        internal global::System.DateTime Expiry
        {
            get
            {
                global::System.DateTime ret = ((global::System.DateTime)(m_privateObject.GetProperty("Expiry")));
                return ret;
            }
            set
            {
                m_privateObject.SetProperty("Expiry", value);
            }
        }

        internal global::System.IO.Stream Data
        {
            get
            {
                global::System.IO.Stream ret = ((global::System.IO.Stream)(m_privateObject.GetProperty("Data")));
                return ret;
            }
            set
            {
                m_privateObject.SetProperty("Data", value);
            }
        }

        internal static object CreatePrivate()
        {
            Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("RssToolkit", "RssToolkit.Rss.DownloadManager+CacheInfo", new object[0]);
            return priv_obj.Target;
        }
    }
    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    internal class RssToolkit_Rss_DownloadManagerAccessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(typeof(global::RssToolkit.Rss.DownloadManager));

        internal RssToolkit_Rss_DownloadManagerAccessor(global::RssToolkit.Rss.DownloadManager target)
            :
                base(target, m_privateType)
        {
        }

        internal static global::RssToolkit.Rss.DownloadManager _downloadManager
        {
            get
            {
                global::RssToolkit.Rss.DownloadManager ret = ((global::RssToolkit.Rss.DownloadManager)(m_privateType.GetStaticField("_downloadManager")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("_downloadManager", value);
            }
        }

        internal int _defaultTtlMinutes
        {
            get
            {
                int ret = ((int)(m_privateObject.GetField("_defaultTtlMinutes")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("_defaultTtlMinutes", value);
            }
        }

        internal string _directoryOnDisk
        {
            get
            {
                string ret = ((string)(m_privateObject.GetField("_directoryOnDisk")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("_directoryOnDisk", value);
            }
        }

        internal static global::RssToolkit.Rss.DownloadManager CreatePrivate()
        {
            object[] args = new object[0];
            Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject(typeof(global::RssToolkit.Rss.DownloadManager), new System.Type[0], args);
            return ((global::RssToolkit.Rss.DownloadManager)(priv_obj.Target));
        }

        internal static string PrepareTempDir()
        {
            object[] args = new object[0];
            string ret = ((string)(m_privateType.InvokeStatic("PrepareTempDir", new System.Type[0], args)));
            return ret;
        }

        internal static string GetTempFileNamePrefixFromUrl(string url)
        {
            object[] args = new object[] {
                url};
            string ret = ((string)(m_privateType.InvokeStatic("GetTempFileNamePrefixFromUrl", new System.Type[] {
                    typeof(string)}, args)));
            return ret;
        }

        internal static int GetTtlFromString(string ttlString, int defaultTtlMinutes)
        {
            object[] args = new object[] {
                ttlString,
                defaultTtlMinutes};
            int ret = ((int)(m_privateType.InvokeStatic("GetTtlFromString", new System.Type[] {
                    typeof(string),
                    typeof(int)}, args)));
            return ret;
        }

        internal global::RssToolkitUnitTest.RssToolkit_Rss_DownloadManager_CacheInfoAccessor GetFeedDom(string url)
        {
            object[] args = new object[] {
                url};
            object _ret_val = m_privateObject.Invoke("GetFeedDom", new System.Type[] {
                    typeof(string)}, args);
            global::RssToolkitUnitTest.RssToolkit_Rss_DownloadManager_CacheInfoAccessor _ret = null;
            if ((_ret_val != null))
            {
                _ret = new global::RssToolkitUnitTest.RssToolkit_Rss_DownloadManager_CacheInfoAccessor(_ret_val);
            }
            global::RssToolkitUnitTest.RssToolkit_Rss_DownloadManager_CacheInfoAccessor ret = _ret;
            return ret;
        }

        internal global::RssToolkitUnitTest.RssToolkit_Rss_DownloadManager_CacheInfoAccessor DownLoadFeedDom(string url)
        {
            object[] args = new object[] {
                url};
            object _ret_val = m_privateObject.Invoke("DownLoadFeedDom", new System.Type[] {
                    typeof(string)}, args);
            global::RssToolkitUnitTest.RssToolkit_Rss_DownloadManager_CacheInfoAccessor _ret = null;
            if ((_ret_val != null))
            {
                _ret = new global::RssToolkitUnitTest.RssToolkit_Rss_DownloadManager_CacheInfoAccessor(_ret_val);
            }
            global::RssToolkitUnitTest.RssToolkit_Rss_DownloadManager_CacheInfoAccessor ret = _ret;
            return ret;
        }

        internal global::RssToolkitUnitTest.RssToolkit_Rss_DownloadManager_CacheInfoAccessor TryLoadFromDisk(string url)
        {
            object[] args = new object[] {
                url};
            object _ret_val = m_privateObject.Invoke("TryLoadFromDisk", new System.Type[] {
                    typeof(string)}, args);
            global::RssToolkitUnitTest.RssToolkit_Rss_DownloadManager_CacheInfoAccessor _ret = null;
            if ((_ret_val != null))
            {
                _ret = new global::RssToolkitUnitTest.RssToolkit_Rss_DownloadManager_CacheInfoAccessor(_ret_val);
            }
            global::RssToolkitUnitTest.RssToolkit_Rss_DownloadManager_CacheInfoAccessor ret = _ret;
            return ret;
        }

        internal void TrySaveToDisk(global::System.Xml.XmlDocument doc, string url, global::System.DateTime utcExpiry)
        {
            object[] args = new object[] {
                doc,
                url,
                utcExpiry};
            m_privateObject.Invoke("TrySaveToDisk", new System.Type[] {
                    typeof(global::System.Xml.XmlDocument),
                    typeof(string),
                    typeof(global::System.DateTime)}, args);
        }
    }
    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    internal class RssToolkit_Rss_RssAggregatorAccessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(typeof(global::RssToolkit.Rss.RssAggregator));

        internal RssToolkit_Rss_RssAggregatorAccessor(global::RssToolkit.Rss.RssAggregator target)
            :
                base(target, m_privateType)
        {
        }

        internal global::System.Threading.AutoResetEvent[] rssEvents
        {
            get
            {
                global::System.Threading.AutoResetEvent[] ret = ((global::System.Threading.AutoResetEvent[])(m_privateObject.GetField("rssEvents")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("rssEvents", value);
            }
        }

        internal string _rssXml
        {
            get
            {
                string ret = ((string)(m_privateObject.GetField("_rssXml")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("_rssXml", value);
            }
        }

        internal void Load(global::RssToolkit.Opml.OpmlDocument opmlDocument)
        {
            object[] args = new object[] {
                opmlDocument};
            m_privateObject.Invoke("Load", new System.Type[] {
                    typeof(global::RssToolkit.Opml.OpmlDocument)}, args);
        }

        internal void LoadRssFeeds(global::RssToolkit.Opml.OpmlDocument opmlDocument)
        {
            object[] args = new object[] {
                opmlDocument};
            m_privateObject.Invoke("LoadRssFeeds", new System.Type[] {
                    typeof(global::RssToolkit.Opml.OpmlDocument)}, args);
        }

        internal void GetRssFeeds(object state)
        {
            object[] args = new object[] {
                state};
            m_privateObject.Invoke("GetRssFeeds", new System.Type[] {
                    typeof(object)}, args);
        }

        internal void NotifySubscribers(global::System.Exception ex, string message, global::RssToolkit.Rss.RssSeverityType severityType)
        {
            object[] args = new object[] {
                ex,
                message,
                severityType};
            m_privateObject.Invoke("NotifySubscribers", new System.Type[] {
                    typeof(global::System.Exception),
                    typeof(string),
                    typeof(global::RssToolkit.Rss.RssSeverityType)}, args);
        }

        internal void MergeRss(string title)
        {
            object[] args = new object[] {
                title};
            m_privateObject.Invoke("MergeRss", new System.Type[] {
                    typeof(string)}, args);
        }
    }
    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    internal class RssToolkit_Rss_RssDocumentAccessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(typeof(global::RssToolkit.Rss.RssDocument));

        internal RssToolkit_Rss_RssDocumentAccessor(global::RssToolkit.Rss.RssDocument target)
            :
                base(target, m_privateType)
        {
        }

        internal string _version
        {
            get
            {
                string ret = ((string)(m_privateObject.GetField("_version")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("_version", value);
            }
        }

        internal global::RssToolkit.Rss.RssChannel _channel
        {
            get
            {
                global::RssToolkit.Rss.RssChannel ret = ((global::RssToolkit.Rss.RssChannel)(m_privateObject.GetField("_channel")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("_channel", value);
            }
        }

        internal string _url
        {
            get
            {
                string ret = ((string)(m_privateObject.GetField("_url")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("_url", value);
            }
        }

        internal string Url
        {
            get
            {
                string ret = ((string)(m_privateObject.GetProperty("Url")));
                return ret;
            }
        }
    }
    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    internal class RssToolkit_Rss_RssHttpHandlerHelperAccessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(typeof(global::RssToolkit.Rss.RssHttpHandlerHelper));

        internal RssToolkit_Rss_RssHttpHandlerHelperAccessor(global::RssToolkit.Rss.RssHttpHandlerHelper target)
            :
                base(target, m_privateType)
        {
        }

        internal static global::RssToolkit.Rss.RssHttpHandlerHelper CreatePrivate()
        {
            object[] args = new object[0];
            Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject(typeof(global::RssToolkit.Rss.RssHttpHandlerHelper), new System.Type[0], args);
            return ((global::RssToolkit.Rss.RssHttpHandlerHelper)(priv_obj.Target));
        }

        internal static void ParseChannelQueryString(global::System.Web.HttpRequest request, out string channelName, out string userName)
        {
            object[] args = new object[] {
                request,
                null,
                null};
            m_privateType.InvokeStatic("ParseChannelQueryString", new System.Type[] {
                    typeof(global::System.Web.HttpRequest),
                    typeof(string).MakeByRefType(),
                    typeof(string).MakeByRefType()}, args);
            channelName = ((string)(args[1]));
            userName = ((string)(args[2]));
        }
    }
    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    internal class RssToolkit_Rss_RssXmlHelperAccessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(typeof(global::RssToolkit.Rss.RssXmlHelper));

        internal RssToolkit_Rss_RssXmlHelperAccessor()
            :
                base(m_privateType)
        {
        }

        internal static string TimeZoneCacheKey
        {
            get
            {
                string ret = ((string)(m_privateType.GetStaticField("TimeZoneCacheKey")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("TimeZoneCacheKey", value);
            }
        }

        internal static double RFCTimeZoneToGMTBias(string zone)
        {
            object[] args = new object[] {
                zone};
            double ret = ((double)(m_privateType.InvokeStatic("RFCTimeZoneToGMTBias", new System.Type[] {
                    typeof(string)}, args)));
            return ret;
        }
    }
    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    internal class RssToolkit_Rss_RssXmlSchemaValidatorAccessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(typeof(global::RssToolkit.Rss.RssXmlSchemaValidator));

        internal RssToolkit_Rss_RssXmlSchemaValidatorAccessor(global::RssToolkit.Rss.RssXmlSchemaValidator target)
            :
                base(target, m_privateType)
        {
        }

        internal bool isValidXml
        {
            get
            {
                bool ret = ((bool)(m_privateObject.GetField("isValidXml")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("isValidXml", value);
            }
        }

        internal string validationError
        {
            get
            {
                string ret = ((string)(m_privateObject.GetField("validationError")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("validationError", value);
            }
        }

        internal void ValidationCallBack(object sender, global::System.Xml.Schema.ValidationEventArgs args)
        {
            object[] _args = new object[] {
                sender,
                args};
            m_privateObject.Invoke("ValidationCallBack", new System.Type[] {
                    typeof(object),
                    typeof(global::System.Xml.Schema.ValidationEventArgs)}, _args);
        }
    }
    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    internal class RssToolkit_Rss_CodeGeneration_ClassInfoAccessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("RssToolkit", "RssToolkit.Rss.CodeGeneration.ClassInfo");

        internal RssToolkit_Rss_CodeGeneration_ClassInfoAccessor(object target)
            :
                base(target, m_privateType)
        {
        }

        internal string name
        {
            get
            {
                string ret = ((string)(m_privateObject.GetField("name")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("name", value);
            }
        }

        internal bool isText
        {
            get
            {
                bool ret = ((bool)(m_privateObject.GetField("isText")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("isText", value);
            }
        }

        internal string namespaceName
        {
            get
            {
                string ret = ((string)(m_privateObject.GetField("namespaceName")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("namespaceName", value);
            }
        }

        internal string Name
        {
            get
            {
                string ret = ((string)(m_privateObject.GetProperty("Name")));
                return ret;
            }
            set
            {
                m_privateObject.SetProperty("Name", value);
            }
        }

        internal bool IsText
        {
            get
            {
                bool ret = ((bool)(m_privateObject.GetProperty("IsText")));
                return ret;
            }
            set
            {
                m_privateObject.SetProperty("IsText", value);
            }
        }

        internal string NamespaceName
        {
            get
            {
                string ret = ((string)(m_privateObject.GetProperty("NamespaceName")));
                return ret;
            }
            set
            {
                m_privateObject.SetProperty("NamespaceName", value);
            }
        }

        internal static object CreatePrivate()
        {
            Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("RssToolkit", "RssToolkit.Rss.CodeGeneration.ClassInfo", new object[0]);
            return priv_obj.Target;
        }
    }

    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    internal class RssToolkit_Rss_CodeGeneration_RssCodeTreeGenerator_ParentInfoAccessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("RssToolkit", "RssToolkit.Rss.CodeGeneration.RssCodeTreeGenerator+ParentInfo");

        internal RssToolkit_Rss_CodeGeneration_RssCodeTreeGenerator_ParentInfoAccessor(object target)
            :
                base(target, m_privateType)
        {
        }

        internal System.Collections.Generic.Dictionary<string, int> ChildCount
        {
            get
            {
                System.Collections.Generic.Dictionary<string, int> ret = ((System.Collections.Generic.Dictionary<string, int>)(m_privateObject.GetProperty("ChildCount")));
                return ret;
            }
        }

        internal static object CreatePrivate()
        {
            object[] args = new object[0];
            Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("RssToolkit", "RssToolkit.Rss.CodeGeneration.RssCodeTreeGenerator+ParentInfo", new System.Type[0], args);
            return priv_obj.Target;
        }
    }
    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    internal class RssToolkit_Rss_CodeGeneration_PropertyInfoAccessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("RssToolkit", "RssToolkit.Rss.CodeGeneration.PropertyInfo");

        internal RssToolkit_Rss_CodeGeneration_PropertyInfoAccessor(object target)
            :
                base(target, m_privateType)
        {
        }

        internal string name
        {
            get
            {
                string ret = ((string)(m_privateObject.GetField("name")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("name", value);
            }
        }

        internal int occurances
        {
            get
            {
                int ret = ((int)(m_privateObject.GetField("occurances")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("occurances", value);
            }
        }

        internal bool isattribute
        {
            get
            {
                bool ret = ((bool)(m_privateObject.GetField("isattribute")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("isattribute", value);
            }
        }

        internal string Name
        {
            get
            {
                string ret = ((string)(m_privateObject.GetProperty("Name")));
                return ret;
            }
            set
            {
                m_privateObject.SetProperty("Name", value);
            }
        }

        internal int Occurances
        {
            get
            {
                int ret = ((int)(m_privateObject.GetProperty("Occurances")));
                return ret;
            }
            set
            {
                m_privateObject.SetProperty("Occurances", value);
            }
        }

        internal bool IsAttribute
        {
            get
            {
                bool ret = ((bool)(m_privateObject.GetProperty("IsAttribute")));
                return ret;
            }
            set
            {
                m_privateObject.SetProperty("IsAttribute", value);
            }
        }

        internal static object CreatePrivate()
        {
            Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("RssToolkit", "RssToolkit.Rss.CodeGeneration.PropertyInfo", new object[0]);
            return priv_obj.Target;
        }
    }
    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    internal class RssToolkit_Rss_CodeGeneration_RssCodeGeneratorAccessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(typeof(global::RssToolkit.Rss.CodeGeneration.RssCodeGenerator));

        internal RssToolkit_Rss_CodeGeneration_RssCodeGeneratorAccessor(global::RssToolkit.Rss.CodeGeneration.RssCodeGenerator target)
            :
                base(target, m_privateType)
        {
        }

        internal static string RssConstant
        {
            get
            {
                string ret = ((string)(m_privateType.GetStaticField("RssConstant")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("RssConstant", value);
            }
        }

        internal static string ChannelConstant
        {
            get
            {
                string ret = ((string)(m_privateType.GetStaticField("ChannelConstant")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("ChannelConstant", value);
            }
        }

        internal static string NamespaceConstant
        {
            get
            {
                string ret = ((string)(m_privateType.GetStaticField("NamespaceConstant")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("NamespaceConstant", value);
            }
        }

        internal static string RssNamespaceConstant
        {
            get
            {
                string ret = ((string)(m_privateType.GetStaticField("RssNamespaceConstant")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("RssNamespaceConstant", value);
            }
        }

        internal static string HttpHandlerNamespaceConstant
        {
            get
            {
                string ret = ((string)(m_privateType.GetStaticField("HttpHandlerNamespaceConstant")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("HttpHandlerNamespaceConstant", value);
            }
        }

        internal static global::RssToolkit.Rss.CodeGeneration.RssCodeGenerator CreatePrivate()
        {
            object[] args = new object[0];
            Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject(typeof(global::RssToolkit.Rss.CodeGeneration.RssCodeGenerator), new System.Type[0], args);
            return ((global::RssToolkit.Rss.CodeGeneration.RssCodeGenerator)(priv_obj.Target));
        }

        internal static string CodeNameFromRssName(string rssName)
        {
            object[] args = new object[] {
                rssName};
            string ret = ((string)(m_privateType.InvokeStatic("CodeNameFromRssName", new System.Type[] {
                    typeof(string)}, args)));
            return ret;
        }

        internal static string CodeParamNameFromRssName(string rssName)
        {
            object[] args = new object[] {
                rssName};
            string ret = ((string)(m_privateType.InvokeStatic("CodeParamNameFromRssName", new System.Type[] {
                    typeof(string)}, args)));
            return ret;
        }

        internal static string CodePrivateNameFromRssName(string rssName)
        {
            object[] args = new object[] {
                rssName};
            string ret = ((string)(m_privateType.InvokeStatic("CodePrivateNameFromRssName", new System.Type[] {
                    typeof(string)}, args)));
            return ret;
        }

        internal static bool NamespaceContainsType(global::System.CodeDom.CodeNamespace nameSpace, string typeName)
        {
            object[] args = new object[] {
                nameSpace,
                typeName};
            bool ret = ((bool)(m_privateType.InvokeStatic("NamespaceContainsType", new System.Type[] {
                    typeof(global::System.CodeDom.CodeNamespace),
                    typeof(string)}, args)));
            return ret;
        }

        internal static bool TypeContainsProperty(global::System.CodeDom.CodeTypeDeclaration type, string propertyToFind)
        {
            object[] args = new object[] {
                type,
                propertyToFind};
            bool ret = ((bool)(m_privateType.InvokeStatic("TypeContainsProperty", new System.Type[] {
                    typeof(global::System.CodeDom.CodeTypeDeclaration),
                    typeof(string)}, args)));
            return ret;
        }

        internal static void AddCodeProperty(string nodeName, global::System.Xml.XmlNodeType nodeType, global::System.CodeDom.CodeTypeReference propertyType, global::System.CodeDom.CodeTypeDeclaration classType, bool collection)
        {
            object[] args = new object[] {
                nodeName,
                nodeType,
                propertyType,
                classType,
                collection};
            m_privateType.InvokeStatic("AddCodeProperty", new System.Type[] {
                    typeof(string),
                    typeof(global::System.Xml.XmlNodeType),
                    typeof(global::System.CodeDom.CodeTypeReference),
                    typeof(global::System.CodeDom.CodeTypeDeclaration),
                    typeof(bool)}, args);
        }

        internal static void GenerateLoadRss(global::System.CodeDom.CodeTypeDeclaration channelType, string url)
        {
            object[] args = new object[] {
                channelType,
                url};
            m_privateType.InvokeStatic("GenerateLoad", new System.Type[] {
                    typeof(global::System.CodeDom.CodeTypeDeclaration),
                    typeof(string)}, args);
        }

        internal static void GenerateToXml(global::System.CodeDom.CodeTypeDeclaration channelType)
        {
            object[] args = new object[] {
                channelType};
            m_privateType.InvokeStatic("GenerateToXml", new System.Type[] {
                    typeof(global::System.CodeDom.CodeTypeDeclaration)}, args);
        }

        internal static void GenerateToDataSet(global::System.CodeDom.CodeTypeDeclaration channelType)
        {
            object[] args = new object[] {
                channelType};
            m_privateType.InvokeStatic("GenerateToDataSet", new System.Type[] {
                    typeof(global::System.CodeDom.CodeTypeDeclaration)}, args);
        }

        internal static void GenerateLoadRssByUrl(global::System.CodeDom.CodeTypeDeclaration channelType)
        {
            object[] args = new object[] {
                channelType};
            m_privateType.InvokeStatic("GenerateLoadRssByUrl", new System.Type[] {
                    typeof(global::System.CodeDom.CodeTypeDeclaration)}, args);
        }

        internal static void GenerateLoadRssByXml(global::System.CodeDom.CodeTypeDeclaration channelType)
        {
            object[] args = new object[] {
                channelType};
            m_privateType.InvokeStatic("GenerateLoadRssByXml", new System.Type[] {
                    typeof(global::System.CodeDom.CodeTypeDeclaration)}, args);
        }

        internal static void GenerateLoadRssFromOpml(global::System.CodeDom.CodeTypeDeclaration channelType)
        {
            object[] args = new object[] {
                channelType};
            m_privateType.InvokeStatic("GenerateLoadRssFromOpml", new System.Type[] {
                    typeof(global::System.CodeDom.CodeTypeDeclaration)}, args);
        }

        internal static void GenerateLoadRssItems(global::System.CodeDom.CodeTypeDeclaration channelType, string itemTypeName)
        {
            object[] args = new object[] {
                channelType,
                itemTypeName};
            m_privateType.InvokeStatic("GenerateLoadRssItems", new System.Type[] {
                    typeof(global::System.CodeDom.CodeTypeDeclaration),
                    typeof(string)}, args);
        }
    }
    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    internal class RssToolkit_Rss_CodeGeneration_RssCodeTreeGeneratorAccessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("RssToolkit", "RssToolkit.Rss.CodeGeneration.RssCodeTreeGenerator");

        internal RssToolkit_Rss_CodeGeneration_RssCodeTreeGeneratorAccessor()
            :
                base(m_privateType)
        {
        }

        internal static object CreatePrivate()
        {
            Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("RssToolkit", "RssToolkit.Rss.CodeGeneration.RssCodeTreeGenerator", new object[0]);
            return priv_obj.Target;
        }
    }
}namespace FrameworkUnitTest
{
[System.Diagnostics.DebuggerStepThrough()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
internal class BaseAccessor {
    
    protected Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject m_privateObject;
    
    protected BaseAccessor(object target, Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType type) {
        m_privateObject = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject(target, type);
    }
    
    protected BaseAccessor(Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType type) : 
            this(null, type) {
    }
    
    internal virtual object Target {
        get {
            return m_privateObject.Target;
        }
    }
    
    public override string ToString() {
        return this.Target.ToString();
    }
    
    public override bool Equals(object obj) {
        if (typeof(BaseAccessor).IsInstanceOfType(obj)) {
            obj = ((BaseAccessor)(obj)).Target;
        }
        return this.Target.Equals(obj);
    }
    
    public override int GetHashCode() {
        return this.Target.GetHashCode();
    }
}



}
