//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RssToolkit.Rss;
using System;
using System.Collections.Generic;
using System.Xml;
using System.Xml.Serialization;



[System.Serializable()]
[System.Xml.Serialization.XmlRoot("rss")]
public class MSNBCRss : RssToolkit.Rss.RssDocumentBase
{

    private string _version;

    private string _media;

    private MSNBCChannel _channel;

    [XmlAttribute("version")]
    public string Version
    {
        get
        {
            return _version;
        }
        set
        {
            _version = value;
        }
    }

    [XmlAttribute("media")]
    public string Media
    {
        get
        {
            return _media;
        }
        set
        {
            _media = value;
        }
    }

    [XmlElement("channel")]
    public MSNBCChannel Channel
    {
        get
        {
            return _channel;
        }
        set
        {
            _channel = value;
        }
    }

    public static MSNBCRss LoadRss()
    {
        MSNBCRss rss;
        rss = MSNBCRss.LoadRss("http://rss.msnbc.msn.com/id/3032091/device/rss/rss.xml");
        return rss;
    }

    public static MSNBCRss LoadRss(string url)
    {
        if (String.IsNullOrEmpty(url))
        {
            throw new ArgumentNullException("url");
        }
        MSNBCRss rss;
        rss = RssXmlHelper.DeserializeFromXmlUsingStringReader<MSNBCRss>(DownloadManager.GetFeed(url));
        return rss;
    }

    public static MSNBCRss LoadRss(System.Xml.XmlDocument doc)
    {
        if (doc == null)
        {
            throw new ArgumentNullException("doc");
        }
        MSNBCRss rss;
        rss = RssXmlHelper.DeserializeFromXmlUsingStringReader<MSNBCRss>(doc.OuterXml);
        return rss;
    }

   

    public static System.Collections.Generic.List<MSNBCItem> LoadRssItems()
    {
        return LoadRss().Channel.Items;
    }

    public override string ToXml()
    {
        return RssXmlHelper.ToXml<MSNBCRss>(this);
    }
}

public class MSNBCChannel
{

    private string _title;

    private string _link;

    private string _description;

    private string _copyright;

    private string _language;

    private MSNBCImage _image;

    private string _lastBuildDate;

    private string _category;

    private string _ttl;

    private List<MSNBCItem> _items;

    [XmlElement("title")]
    public string Title
    {
        get
        {
            return _title;
        }
        set
        {
            _title = value;
        }
    }

    [XmlElement("link")]
    public string Link
    {
        get
        {
            return _link;
        }
        set
        {
            _link = value;
        }
    }

    [XmlElement("description")]
    public string Description
    {
        get
        {
            return _description;
        }
        set
        {
            _description = value;
        }
    }

    [XmlElement("copyright")]
    public string Copyright
    {
        get
        {
            return _copyright;
        }
        set
        {
            _copyright = value;
        }
    }

    [XmlElement("language")]
    public string Language
    {
        get
        {
            return _language;
        }
        set
        {
            _language = value;
        }
    }

    [XmlElement("image")]
    public MSNBCImage Image
    {
        get
        {
            return _image;
        }
        set
        {
            _image = value;
        }
    }

    [XmlElement("lastBuildDate")]
    public string LastBuildDate
    {
        get
        {
            return _lastBuildDate;
        }
        set
        {
            _lastBuildDate = value;
        }
    }

    [XmlElement("category")]
    public string Category
    {
        get
        {
            return _category;
        }
        set
        {
            _category = value;
        }
    }

    [XmlElement("ttl")]
    public string Ttl
    {
        get
        {
            return _ttl;
        }
        set
        {
            _ttl = value;
        }
    }

    [XmlElement("item")]
    public List<MSNBCItem> Items
    {
        get
        {
            return _items;
        }
        set
        {
            _items = value;
        }
    }
}

public class MSNBCImage
{

    private string _url;

    private string _title;

    private string _link;

    [XmlElement("url")]
    public string Url
    {
        get
        {
            return _url;
        }
        set
        {
            _url = value;
        }
    }

    [XmlElement("title")]
    public string Title
    {
        get
        {
            return _title;
        }
        set
        {
            _title = value;
        }
    }

    [XmlElement("link")]
    public string Link
    {
        get
        {
            return _link;
        }
        set
        {
            _link = value;
        }
    }
}

public class MSNBCItem
{

    private string _title;

    private string _description;

    private string _link;

    private string _pubDate;

    private string _category;

    private MSNBCGuid _guid;

    private MSNBCContent _content;

    [XmlElement("title")]
    public string Title
    {
        get
        {
            return _title;
        }
        set
        {
            _title = value;
        }
    }

    [XmlElement("description")]
    public string Description
    {
        get
        {
            return _description;
        }
        set
        {
            _description = value;
        }
    }

    [XmlElement("link")]
    public string Link
    {
        get
        {
            return _link;
        }
        set
        {
            _link = value;
        }
    }

    [XmlElement("pubDate")]
    public string PubDate
    {
        get
        {
            return _pubDate;
        }
        set
        {
            _pubDate = value;
        }
    }

    [XmlElement("category")]
    public string Category
    {
        get
        {
            return _category;
        }
        set
        {
            _category = value;
        }
    }

    [XmlElement("guid")]
    public MSNBCGuid Guid
    {
        get
        {
            return _guid;
        }
        set
        {
            _guid = value;
        }
    }

    [XmlElement("content")]
    public MSNBCContent Content
    {
        get
        {
            return _content;
        }
        set
        {
            _content = value;
        }
    }
}

public class MSNBCGuid
{

    private string _isPermaLink;

    [XmlAttribute("isPermaLink")]
    public string IsPermaLink
    {
        get
        {
            return _isPermaLink;
        }
        set
        {
            _isPermaLink = value;
        }
    }
}

public class MSNBCContent
{

    private string _medium;

    private MSNBCCredit _credit;

    private MSNBCPlayer _player;

    private MSNBCThumbnail _thumbnail;

    private string _copyright;

    private string _text;

    private string _url;

    [XmlAttribute("medium")]
    public string Medium
    {
        get
        {
            return _medium;
        }
        set
        {
            _medium = value;
        }
    }

    [XmlElement("credit")]
    public MSNBCCredit Credit
    {
        get
        {
            return _credit;
        }
        set
        {
            _credit = value;
        }
    }

    [XmlElement("player")]
    public MSNBCPlayer Player
    {
        get
        {
            return _player;
        }
        set
        {
            _player = value;
        }
    }

    [XmlElement("thumbnail")]
    public MSNBCThumbnail Thumbnail
    {
        get
        {
            return _thumbnail;
        }
        set
        {
            _thumbnail = value;
        }
    }

    [XmlElement("copyright")]
    public string Copyright
    {
        get
        {
            return _copyright;
        }
        set
        {
            _copyright = value;
        }
    }

    [XmlElement("text")]
    public string Text
    {
        get
        {
            return _text;
        }
        set
        {
            _text = value;
        }
    }

    [XmlAttribute("url")]
    public string Url
    {
        get
        {
            return _url;
        }
        set
        {
            _url = value;
        }
    }
}

public class MSNBCCredit
{

    private string _role;

    [XmlAttribute("role")]
    public string Role
    {
        get
        {
            return _role;
        }
        set
        {
            _role = value;
        }
    }
}

public class MSNBCPlayer
{

    private string _url;

    [XmlAttribute("url")]
    public string Url
    {
        get
        {
            return _url;
        }
        set
        {
            _url = value;
        }
    }
}

public class MSNBCThumbnail
{

    private string _url;

    [XmlAttribute("url")]
    public string Url
    {
        get
        {
            return _url;
        }
        set
        {
            _url = value;
        }
    }
}

public class MSNBCHttpHandlerBase : RssToolkit.Rss.RssHttpHandlerBase<MSNBCRss>
{
}
