//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1318
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RssToolkit.Rss;
using System;
using System.Collections.Generic;
using System.Xml;
using System.Xml.Serialization;



[System.Serializable()]
[System.Xml.Serialization.XmlRoot("rss")]
public class YoutubeRss : RssToolkit.Rss.RssDocumentBase
{

    private string _version;

    private YoutubeChannel _channel;

    [XmlAttribute("version")]
    public string Version
    {
        get
        {
            return _version;
        }
        set
        {
            _version = value;
        }
    }

    [XmlElement("channel")]
    public YoutubeChannel Channel
    {
        get
        {
            return _channel;
        }
        set
        {
            _channel = value;
        }
    }

    public static YoutubeRss Load()
    {
        YoutubeRss doc;
        doc = YoutubeRss.Load(new System.Uri("http://youtube.com/rss/global/top_favorites.rss"));
        return doc;
    }

    public static YoutubeRss Load(System.Uri url)
    {
        if ((url == null))
        {
            throw new System.ArgumentNullException();
        }
        YoutubeRss doc;
        doc = RssDocumentBase.Load<YoutubeRss>(url);
        return doc;
    }

    public static YoutubeRss Load(System.Xml.XmlTextReader reader)
    {
        if ((reader == null))
        {
            throw new System.ArgumentNullException();
        }
        YoutubeRss doc;
        doc = RssDocumentBase.Load<YoutubeRss>(reader);
        return doc;
    }

    public static YoutubeRss Load(string xml)
    {
        if (String.IsNullOrEmpty(xml))
        {
            throw new System.ArgumentNullException();
        }
        YoutubeRss doc;
        doc = RssDocumentBase.Load<YoutubeRss>(xml);
        return doc;
    }

    public static System.Collections.Generic.List<YoutubeItem> LoadRssItems()
    {
        return Load().Channel.Items;
    }

    public override string ToXml(RssToolkit.Rss.DocumentType outputType)
    {
        return RssDocumentBase.ToXml<YoutubeRss>(outputType, this);
    }

    public virtual System.Data.DataSet ToDataSet()
    {
        return RssXmlHelper.ToDataSet(ToXml(DocumentType.Rss));
    }
}

public class YoutubeChannel
{

    private string _title;

    private string _link;

    private YoutubeImage _image;

    private string _description;

    private List<YoutubeItem> _items;

    [XmlElement("title", Namespace = "http://search.yahoo.com/mrss/")]
    public string Title
    {
        get
        {
            return _title;
        }
        set
        {
            _title = value;
        }
    }

    [XmlElement("link")]
    public string Link
    {
        get
        {
            return _link;
        }
        set
        {
            _link = value;
        }
    }

    [XmlElement("image")]
    public YoutubeImage Image
    {
        get
        {
            return _image;
        }
        set
        {
            _image = value;
        }
    }

    [XmlElement("description")]
    public string Description
    {
        get
        {
            return _description;
        }
        set
        {
            _description = value;
        }
    }

    [XmlElement("item")]
    public List<YoutubeItem> Items
    {
        get
        {
            return _items;
        }
        set
        {
            _items = value;
        }
    }
}

public class YoutubeImage
{

    private string _url;

    private string _link;

    private string _title;

    private string _height;

    private string _width;

    [XmlElement("url")]
    public string Url
    {
        get
        {
            return _url;
        }
        set
        {
            _url = value;
        }
    }

    [XmlElement("link")]
    public string Link
    {
        get
        {
            return _link;
        }
        set
        {
            _link = value;
        }
    }

    [XmlElement("title", Namespace = "http://search.yahoo.com/mrss/")]
    public string Title
    {
        get
        {
            return _title;
        }
        set
        {
            _title = value;
        }
    }

    [XmlElement("height")]
    public string Height
    {
        get
        {
            return _height;
        }
        set
        {
            _height = value;
        }
    }

    [XmlElement("width")]
    public string Width
    {
        get
        {
            return _width;
        }
        set
        {
            _width = value;
        }
    }
}

public class YoutubeItem
{

    private string _author;

    private List<string> _titles;

    private string _link;

    private string _description;

    private YoutubeGuid _guid;

    private string _pubDate;

    private YoutubePlayer _player;

    private YoutubeThumbnail _thumbnail;

    private YoutubeCategory _category;

    private string _credit;

    private YoutubeEnclosure _enclosure;

    [XmlElement("author")]
    public string Author
    {
        get
        {
            return _author;
        }
        set
        {
            _author = value;
        }
    }

    [XmlElement("title", Namespace = "http://search.yahoo.com/mrss/")]
    public List<string> Titles
    {
        get
        {
            return _titles;
        }
        set
        {
            _titles = value;
        }
    }

    [XmlElement("link")]
    public string Link
    {
        get
        {
            return _link;
        }
        set
        {
            _link = value;
        }
    }

    [XmlElement("description")]
    public string Description
    {
        get
        {
            return _description;
        }
        set
        {
            _description = value;
        }
    }

    [XmlElement("guid")]
    public YoutubeGuid Guid
    {
        get
        {
            return _guid;
        }
        set
        {
            _guid = value;
        }
    }

    [XmlElement("pubDate")]
    public string PubDate
    {
        get
        {
            return _pubDate;
        }
        set
        {
            _pubDate = value;
        }
    }

    [XmlElement("player", Namespace = "http://search.yahoo.com/mrss/")]
    public YoutubePlayer Player
    {
        get
        {
            return _player;
        }
        set
        {
            _player = value;
        }
    }

    [XmlElement("thumbnail", Namespace = "http://search.yahoo.com/mrss/")]
    public YoutubeThumbnail Thumbnail
    {
        get
        {
            return _thumbnail;
        }
        set
        {
            _thumbnail = value;
        }
    }

    [XmlElement("category", Namespace = "http://search.yahoo.com/mrss/")]
    public YoutubeCategory Category
    {
        get
        {
            return _category;
        }
        set
        {
            _category = value;
        }
    }

    [XmlElement("credit", Namespace = "http://search.yahoo.com/mrss/")]
    public string Credit
    {
        get
        {
            return _credit;
        }
        set
        {
            _credit = value;
        }
    }

    [XmlElement("enclosure")]
    public YoutubeEnclosure Enclosure
    {
        get
        {
            return _enclosure;
        }
        set
        {
            _enclosure = value;
        }
    }
}

public class YoutubeGuid
{

    private string _isPermaLink;

    private string _text;

    [XmlAttribute("isPermaLink")]
    public string IsPermaLink
    {
        get
        {
            return _isPermaLink;
        }
        set
        {
            _isPermaLink = value;
        }
    }

    [XmlText()]
    public string Text
    {
        get
        {
            return _text;
        }
        set
        {
            _text = value;
        }
    }
}

public class YoutubePlayer
{

    private string _url;

    [XmlAttribute("url")]
    public string Url
    {
        get
        {
            return _url;
        }
        set
        {
            _url = value;
        }
    }
}

public class YoutubeThumbnail
{

    private string _url;

    private string _width;

    private string _height;

    [XmlAttribute("url")]
    public string Url
    {
        get
        {
            return _url;
        }
        set
        {
            _url = value;
        }
    }

    [XmlAttribute("width")]
    public string Width
    {
        get
        {
            return _width;
        }
        set
        {
            _width = value;
        }
    }

    [XmlAttribute("height")]
    public string Height
    {
        get
        {
            return _height;
        }
        set
        {
            _height = value;
        }
    }
}

public class YoutubeCategory
{

    private string _label;

    private string _text;

    [XmlAttribute("label")]
    public string Label
    {
        get
        {
            return _label;
        }
        set
        {
            _label = value;
        }
    }

    [XmlText()]
    public string Text
    {
        get
        {
            return _text;
        }
        set
        {
            _text = value;
        }
    }
}

public class YoutubeEnclosure
{

    private string _url;

    private string _duration;

    private string _type;

    [XmlAttribute("url")]
    public string Url
    {
        get
        {
            return _url;
        }
        set
        {
            _url = value;
        }
    }

    [XmlAttribute("duration")]
    public string Duration
    {
        get
        {
            return _duration;
        }
        set
        {
            _duration = value;
        }
    }

    [XmlAttribute("type")]
    public string Type
    {
        get
        {
            return _type;
        }
        set
        {
            _type = value;
        }
    }
}

public class YoutubeHttpHandlerBase : RssToolkit.Rss.RssHttpHandlerBase<YoutubeRss>
{
}
