// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using RssToolkit.Opml;
namespace RssToolkitUnitTest
{
    /// <summary>
    ///This is a test class for RssToolkit.Opml.OpmlOutline and is intended
    ///to contain all RssToolkit.Opml.OpmlOutline Unit Tests
    ///</summary>
    [TestClass()]
    public class OpmlOutlineTest
    {
        private TestContext testContextInstance;
        private static OpmlDocument target;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        [ClassInitialize()]
        public static void MyClassInitialize(TestContext testContext)
        {
            target = RssToolkitUnitTest.Utility.RssUtility.GetOpmlDocumentFromXml();
        }

        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for HtmlUrl
        ///</summary>
        [TestMethod()]
        public void OpmlOutlineHtmlUrlTest()
        {
            Assert.AreEqual("http://news.bbc.co.uk/go/click/rss/0.91/public/-/1/hi/default.stm", target.Body.Outlines[0].HtmlUrl, "RssToolkit.Opml.OpmlDocument.Head was not set correctly.");
            Assert.AreEqual("http://news.com.com/", target.Body.Outlines[1].HtmlUrl, "RssToolkit.Opml.OpmlDocument.Head was not set correctly.");
        }

        /// <summary>
        ///A test for Text
        ///</summary>
        [TestMethod()]
        public void OpmlOutlineTextTest()
        {
            Assert.AreEqual("BBC News | News Front Page | UK Edition", target.Body.Outlines[0].Text, "RssToolkit.Opml.OpmlDocument.Head was not set correctly.");
            Assert.AreEqual("CNET News.com", target.Body.Outlines[1].Text, "RssToolkit.Opml.OpmlDocument.Head was not set correctly.");
        }

        /// <summary>
        ///A test for Title
        ///</summary>
        [TestMethod()]
        public void OpmlOutlineTitleTest()
        {
            Assert.AreEqual("BBC News | News Front Page | UK Edition", target.Body.Outlines[0].Title, "RssToolkit.Opml.OpmlDocument.Head was not set correctly.");
            Assert.AreEqual("CNET News.com", target.Body.Outlines[1].Title, "RssToolkit.Opml.OpmlDocument.Head was not set correctly.");
        }

        /// <summary>
        ///A test for Type
        ///</summary>
        [TestMethod()]
        public void OpmlOutlineTypeTest()
        {
            Assert.AreEqual("rss", target.Body.Outlines[0].Type, "RssToolkit.Opml.OpmlDocument.Head was not set correctly.");
            Assert.AreEqual("rss", target.Body.Outlines[1].Type, "RssToolkit.Opml.OpmlDocument.Head was not set correctly.");
        }

        /// <summary>
        ///A test for XmlUrl
        ///</summary>
        [TestMethod()]
        public void OpmlOutlineXmlUrlTest()
        {
            Assert.AreEqual("http://news.bbc.co.uk/rss/newsonline_uk_edition/front_page/rss091.xml", target.Body.Outlines[0].XmlUrl, "RssToolkit.Opml.OpmlDocument.Head was not set correctly.");
            Assert.AreEqual("http://news.com.com/2547-1_3-0-5.xml", target.Body.Outlines[1].XmlUrl, "RssToolkit.Opml.OpmlDocument.Head was not set correctly.");
        }
    }
}