// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
namespace RssToolkitUnitTest
{
    /// <summary>
    ///This is a test class for RssToolkit.Rss.CodeGeneration.ClassInfo and is intended
    ///to contain all RssToolkit.Rss.CodeGeneration.ClassInfo Unit Tests
    ///</summary>
    [TestClass()]
    public class ClassInfoTest
    {
        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for Name
        ///</summary>
        [DeploymentItem("RssToolkit.dll")]
        [TestMethod()]
        public void ClassInfoNameTest()
        {
            object target = RssToolkitUnitTest.RssToolkit_Rss_CodeGeneration_ClassInfoAccessor.CreatePrivate();
            string val = "Rss";
            RssToolkitUnitTest.RssToolkit_Rss_CodeGeneration_ClassInfoAccessor accessor = new RssToolkitUnitTest.RssToolkit_Rss_CodeGeneration_ClassInfoAccessor(target);
            accessor.Name = val;

            Assert.AreEqual(val, accessor.Name, "RssToolkit.Rss.CodeGeneration.ClassInfo.Name was not set correctly.");
        }
    }
}
